Vagrant::Config.run do |config|
  # config.vm.boot_mode = :gui

  # DevStack
  config.vm.define :devstack do |devstack|  
    devstack.vm.box = 'ubuntu-1110-server-amd64'
    devstack.vm.box_url = 'http://timhuegdon.com/vagrant-boxes/ubuntu-11.10.box'
    devstack.vm.host_name = 'devstack'
    devstack.vm.network :hostonly, "10.10.10.4"
    devstack.vm.network :hostonly, "192.168.3.4"
    devstack.vm.customize [
      "modifyvm", :id,
      "--name", "novaservices",
      "--memory", "2048"
    ]
    devstack.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      # puppet.options = ["--debug", "--templatedir templates"]
      puppet.options = ["--templatedir templates"]
    end
  end

  # OpenStack novaservices (All components of OpenStack except for nova-compute)
  config.vm.define :novaservices_ubuntu do |novaservices|  
    novaservices.vm.box = 'ubuntu-1110-server-amd64'
    novaservices.vm.box_url = 'http://timhuegdon.com/vagrant-boxes/ubuntu-11.10.box'
    novaservices.vm.host_name = 'novaservices'
    novaservices.vm.network :hostonly, "10.10.11.2"
    novaservices.vm.network :hostonly, "192.168.11.2"
    # novaservices.vm.customize [
    #   "modifyvm", :id,
    #   "--name", "novaservices",
    #   "--memory", "1024"
    # ]
    novaservices.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      # puppet.options = ["--debug", "--templatedir templates"]
      puppet.options = ["--templatedir templates"]
    end
  end

  # OpenStack novaservices (All components of OpenStack except for nova-compute)
  config.vm.define :novaservices_centos do |novaservices| 
    novaservices.vm.box = 'centos-6.0-x86_64'
    novaservices.vm.box_url = 'http://dl.dropbox.com/u/1627760/centos-6.0-x86_64.box'
    novaservices.vm.host_name = 'novaservices'
    novaservices.vm.network :hostonly, "10.10.12.2"
    novaservices.vm.network :hostonly, "192.168.12.2"
    # novaservices.vm.customize [
    #   "modifyvm", :id,
    #   "--name", "novaservices",
    #   "--memory", "1024"
    # ]
    novaservices.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = ["--templatedir templates"]
    end
  end

  # OpenStack novacompute (OpenStack nova-compute)
  config.vm.define :novacompute_centos do |novacompute| 
    novacompute.vm.box = 'centos-6.0-x86_64'
    novacompute.vm.box_url = 'http://dl.dropbox.com/u/1627760/centos-6.0-x86_64.box'
    novacompute.vm.host_name = 'novaservices'
    novacompute.vm.network :hostonly, "10.10.12.3"
    novacompute.vm.network :hostonly, "192.168.12.3"
    novacompute.vm.customize [
      "modifyvm", :id,
      "--name", "novaservices",
      "--memory", "1024"
    ]
    novacompute.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = ["--templatedir templates"]
    end
  end
  
  # Yum server
  config.vm.define :yum do |yum| 
    yum.vm.box = 'centos-6.0-x86_64'
    yum.vm.box_url = 'http://dl.dropbox.com/u/1627760/centos-6.0-x86_64.box'
    yum.vm.host_name = 'yum'
    yum.vm.network :hostonly, "10.10.12.3"
    yum.vm.network :hostonly, "192.168.12.3"
    # yum.vm.customize [
    #   "modifyvm", :id,
    #   "--name", "yum",
    #   "--memory", "1024"
    # ]
    yum.vm.provision :puppet do |puppet|
      puppet.module_path = ['puppet/modules','puppet-master/modules']
      puppet.manifest_file = 'site.pp'
      puppet.options = ["--templatedir templates"]
    end
  end
  
end
